### ISSUE TITLE
Unable to run: sudo brew services start spoof-mac

### ISSUE THREAD

**Issue by mkelley33** [feross/SpoofMAC#117]
I get the following error when I try to run `sudo brew services start spoof-mac` on MacOS Sonoma 14.3.1

This started happening after I installed MongoDB Community Edition 7.0

```shell
Warning: Taking root:admin ownership of some spoof-mac paths:
  /opt/homebrew/Cellar/spoof-mac/2.1.1_5/libexec/bin
  /opt/homebrew/Cellar/spoof-mac/2.1.1_5/libexec/bin/spoof-mac
  /opt/homebrew/opt/spoof-mac
  /opt/homebrew/opt/spoof-mac/bin
  /opt/homebrew/var/homebrew/linked/spoof-mac
This will require manual removal of these paths using `sudo rm` on
brew upgrade/reinstall/uninstall.
Bootstrap failed: 5: Input/output error
Error: Failure while executing; `/bin/launchctl bootstrap system /Library/LaunchDaemons/homebrew.mxcl.spoof-mac.plist` exited with 5.
```

**Comment by DIGIX666** [comment]
Hi @mkelley33 

Did you run sudo `brew services start spoof-mac`  to install spoof-mac? 
I have executed the command `brew install spoof-mac`  and  `spoof-mac.py --help`  and it works fine for me.

<img width="1050" alt="SCR-20240419-lfvh" src="https://github.com/feross/SpoofMAC/assets/90353329/cef441e3-5220-4d83-bad3-900e41345ed9">

**Comment by mkelley33** [comment]
I ran `brew install spoof-mac`, then I ran `sudo brew services start spoof-mac`, which gave me the following error:
 
Warning: Taking root:admin ownership of some spoof-mac paths:
  /opt/homebrew/Cellar/spoof-mac/2.1.1_5/libexec/bin
  /opt/homebrew/Cellar/spoof-mac/2.1.1_5/libexec/bin/spoof-mac
  /opt/homebrew/opt/spoof-mac
  /opt/homebrew/opt/spoof-mac/bin
  /opt/homebrew/var/homebrew/linked/spoof-mac
This will require manual removal of these paths using `sudo rm` on
brew upgrade/reinstall/uninstall.
Bootstrap failed: 5: Input/output error
Error: Failure while executing; `/bin/launchctl bootstrap system /Library/LaunchDaemons/homebrew.mxcl.spoof-mac.plist` exited with 5.

@DIGIX666 Is there another way I should be starting the launch daemon?

**Comment by mkelley33** [comment]
@DIGIX666 then when I run `brew services start spoof-mac` I get the following, which is helpful, but I'd like spoof-mac to start at startup.

Warning: spoof-mac must be run as root to start at system startup!
==> Successfully started `spoof-mac` (label: homebrew.mxcl.spoof-mac)

Do you know of a way around this?

**Comment by DIGIX666** [comment]
Oh ok, I understand your request better now.
Have you already tried the command `spoof-mac.py --help` to see if it returns the `USAGE` ?
<img width="544" alt="SCR-20240419-nauk" src="https://github.com/feross/SpoofMAC/assets/90353329/8278160b-4690-40d0-acc1-71430c463f42">

Yes, your command `sudo brew services start spoof-mac` is indeed correct.

it's strange because the path for file `homebrew.mxcl.spoof-mac.plist` is not the same, me is <img width="911" alt="SCR-20240419-nhml" src="https://github.com/feross/SpoofMAC/assets/90353329/9a87bfbf-8507-4ef2-8db0-9cf12a7721eb"> and you is `/bin/launchctl bootstrap system /Library/LaunchDaemons/homebrew.mxcl.spoof-mac.plist`

**Comment by mkelley33** [comment]
@DIGIX666 I did try the --help command thanks, but I see this now when manually attempting to spoof:

```
sudo spoof-mac randomize en0
Password:
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
WARNING: The airport command line tool is deprecated and will be removed in a future release.
For diagnosing Wi-Fi related issues, use the Wireless Diagnostics app or wdutil command line tool.
ifconfig: ioctl (SIOCAIFADDR): Can't assign requested address
Traceback (most recent call last):
  File "/opt/homebrew/bin/spoof-mac", line 138, in <module>
    sys.exit(main(arguments, root_or_admin))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/bin/spoof-mac", line 118, in main
    set_interface_mac(device, target_mac, port)
  File "/opt/homebrew/Cellar/spoof-mac/2.1.1_5/libexec/lib/python3.12/site-packages/spoofmac/interface.py", line 540, in set_interface_mac
    spoofer.set_interface_mac(device, mac, port)
  File "/opt/homebrew/Cellar/spoof-mac/2.1.1_5/libexec/lib/python3.12/site-packages/spoofmac/interface.py", line 450, in set_interface_mac
    subprocess.check_call([
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ifconfig', 'en0', 'ether', '08:00:27:1C:1D:6B']' returned non-zero exit status 1.
```

**Comment by DIGIX666** [comment]
@mkelley33 
It's normal, I have the same problem too. To successfully change your MAC address, you must `forget` the Wi-Fi network you are connected to and then run the command `sudo spoof-mac.py randomize Wi-Fi` or `sudo spoof-mac.py randomize en0` . After that, reconnect to your Wi-Fi network and check the change with `sudo spoof-mac.py list` .
