### ISSUE TITLE
ipconfig error Sonoma 14.4

### ISSUE THREAD

**Issue by brownbread69** [feross/SpoofMAC#118]
ipconfig is deprecated. I see this was addressed in the change log, but with the most recent version still cannot get it to work right.

----------

WARNING: The airport command line tool is deprecated and will be removed in a future release.
For diagnosing Wi-Fi related issues, use the Wireless Diagnostics app or wdutil command line tool.
ifconfig: ioctl (SIOCAIFADDR): Can't assign requested address Traceback (most recent call last):
  File "/opt/homebrew/bin/spoof-mac", line 138, in <module>
    sys.exit(main(arguments, root_or_admin))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/bin/spoof-mac", line 118, in main
    set_interface_mac(device, target_mac, port)
  File "/opt/homebrew/Cellar/spoof-mac/2.1.1_5/libexec/lib/python3.12/site-packages/spoofmac/interface.py", line 540, in set_interface_mac
    spoofer.set_interface_mac(device, mac, port)
  File "/opt/homebrew/Cellar/spoof-mac/2.1.1_5/libexec/lib/python3.12/site-packages/spoofmac/interface.py", line 450, in set_interface_mac
    subprocess.check_call([
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ifconfig', 'en0', 'ether', '08:00:27:43:13:E6']' returned non-zero exit status 1.

**Comment by minnesnowtawastaken** [comment]
I was able to work around this issue by first disabling wifi on my M1 Air (running 4.1), then running the spoof-mac command. Running the command will also re-enable wifi.

**Comment by brownbread69** [comment]
This worked, thank you. Although it does say it will not work in the future due to deprecation of the ipconfig tool. I hope there is a fix in the works.

**Comment by danydin** [comment]
same issue, doing what you said solve it , but i hope for a perm fix..

**Comment by Keyesb108** [comment]
> I was able to work around this issue by first disabling wifi on my M1 Air (running 4.1), then running the spoof-mac command. Running the command will also re-enable wifi.

thank you so much it now work on my macbook air m2

**Comment by gaetansenn** [comment]
Thanks @minnesnowtawastaken this worked for me ;)

**Comment by ar5hil** [comment]
@minnesnowtawastaken it doesn't seem to work for me i am using `ifconfig en0 down` but as soon as i use `sudo spoof-mac randomize en0` wifi restarts with the same mac address

**Comment by ar5hil** [comment]
Found a Trick and it is working

Thanks @aaronleetw, @DarkNero69!

@artkiver developed a new version that supports macOS Sonoma 14.4+ on branch v0.2-draft.

Please let @artkiver know if the new version does the job:

```
git clone -b v0.2-draft https://github.com/shilch/macchanger
cd macchanger
make
./macchanger
```

Thank you!

**Comment by brownbread69** [comment]
This program only works on Sonoma 14.4.1 when the wifi device is enabled but then disconnected from all networks. Otherwise gives error message: " ERROR:   This device / interface has no MAC address to set.”

**Comment by fharper** [comment]
It also keep the same mac address for me when using `sudo spoof-mac randomize en0` after turning off the wifi.

**Comment by sh4tteredd** [comment]
https://github.com/feross/SpoofMAC/pull/122

**Comment by 2ge** [comment]
@ar5hil thanks so much, finally something, which is really working. Hard to find this one.
