### ISSUE TITLE
Error when mac adresse begin with a number and letter (ie 9C:11:22:33:44:55)

### ISSUE THREAD

**Issue by arnogues** [feross/SpoofMAC#45]
This is the error I got : 
```
sudo spoof-mac.py set "9C:11:22:33:44:55" "Wi-Fi"
Traceback (most recent call last):
  File "/usr/local/bin/spoof-mac.py", line 4, in <module>
    __import__('pkg_resources').run_script('SpoofMAC==2.0.4', 'spoof-mac.py')
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 534, in run_script
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources.py", line 1445, in run_script
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SpoofMAC-2.0.4-py2.7.egg/EGG-INFO/scripts/spoof-mac.py", line 138, in <module>
    
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SpoofMAC-2.0.4-py2.7.egg/EGG-INFO/scripts/spoof-mac.py", line 94, in main
    
ValueError: invalid literal for int() with base 10: 'C'
````
if i replace 9C by 9D I got the same error, if I replace the 'C' by a number, it works.

**Comment by feross** [comment]
Thanks for the report. Released 2.0.5 with a fix.
