### ISSUE TITLE
error when second digit is c

### ISSUE THREAD

**Issue by jregenstein** [feross/SpoofMAC#47]
Here's the command that caused the error:

```
08:16:55 (master) ~/PycharmProjects/SpoofMAC$ sudo spoof-mac.py set 5C:96:9d:05:69:a5 en0
Traceback (most recent call last):
  File "/usr/local/bin/spoof-mac.py", line 5, in <module>
    pkg_resources.run_script('SpoofMAC==2.0.4', 'spoof-mac.py')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 492, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1357, in run_script
    exec_(script_code, namespace, namespace)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 47, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/SpoofMAC-2.0.4-py2.7.egg/EGG-INFO/scripts/spoof-mac.py", line 138, in <module>
    
  File "/Library/Python/2.7/site-packages/SpoofMAC-2.0.4-py2.7.egg/EGG-INFO/scripts/spoof-mac.py", line 94, in main
    
ValueError: invalid literal for int() with base 10: 'C'
```

I fixed the problem by commenting out lines 94 and 95 in spoof-mac.py, but I'm guessing you want a prettier solution.

**Comment by TkTech** [comment]
Already resolved in master.
