### ISSUE TITLE
No script named 'spoof-mac.py'(MacBookPro)

### ISSUE THREAD

**Issue by Sicmatr1x** [feross/SpoofMAC#76]
I use tool Homebrew to install both python2.7 and the python3.6 on my MacBookPro.
And the SpoofMAC I install by `python3 setup.py install`.

I successful finish installs a command-line script called spoof-mac.py, but it couldn't work when I use command "spoof-mac.py --help".

`sicmatr1xdeMacBook-Pro:~ sicmatr1x$ spoof-mac.py --help
Traceback (most recent call last):
  File "/usr/local/bin/spoof-mac.py", line 4, in <module>
    __import__('pkg_resources').run_script('SpoofMAC==2.1.1', 'spoof-mac.py')
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1509, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'spoof-mac.py'`

**Comment by feross** [comment]
Unclear what the issue is to me. You might try using https://github.com/feross/spoof instead.
