### ISSUE TITLE
spoof-mac.py list Error

### ISSUE THREAD

**Issue by javigines** [feross/SpoofMAC#77]
```
C:\WINDOWS\system32>spoof-mac.py list
Traceback (most recent call last):
  File "C:\Users\####\AppData\Local\Programs\Python\Python36-32\Scripts\spoof-mac.py", line 138, in <module>
    sys.exit(main(arguments, root_or_admin))
  File "C:\Users\####\AppData\Local\Programs\Python\Python36-32\Scripts\spoof-mac.py", line 76, in main
    list_interfaces(args, spoofer)
  File "C:\Users\####\AppData\Local\Programs\Python\Python36-32\Scripts\spoof-mac.py", line 56, in list_interfaces
    for port, device, address, current_address in spoofer.find_interfaces(targets=targets):
  File "c:\users\####\appdata\local\programs\python\python36-32\lib\site-packages\spoofmac\interface.py", line 266, in find_interfaces
    output = self.get_ipconfig_all()
  File "c:\users\####\appdata\local\programs\python\python36-32\lib\site-packages\spoofmac\interface.py", line 230, in get_ipconfig_all
    return result.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa2 in position 13: ordinal not in range(128)
```

**Comment by shirshak55** [comment]
try reinstalling?

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.

**Comment by clemenswasser** [comment]
Same issue over here.
