### ISSUE TITLE
List command not working.

### ISSUE THREAD

**Issue by oscardobsonbrown** [feross/SpoofMAC#90]
``` C:\Users\my_user\SpoofMAC>spoof-mac.py list --wifi
Traceback (most recent call last):
  File "C:\Users\my_user\AppData\Local\Programs\Python\Python36-32\Scripts\spoof-mac.py", line 4, in <module>
    __import__('pkg_resources').run_script('SpoofMAC==2.1.1', 'spoof-mac.py')
  File "C:\Users\my_user\.windows-build-tools\python27\lib\site-packages\pkg_resources\__init__.py", line 3017, in <module>
    @_call_aside
  File "C:\Users\my_user\.windows-build-tools\python27\lib\site-packages\pkg_resources\__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "C:\Users\my_user\.windows-build-tools\python27\lib\site-packages\pkg_resources\__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Users\my_user\.windows-build-tools\python27\lib\site-packages\pkg_resources\__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "C:\Users\my_usern\.windows-build-tools\python27\lib\site-packages\pkg_resources\__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Users\my_user\.windows-build-tools\python27\lib\site-packages\pkg_resources\__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'SpoofMAC==2.1.1' distribution was not found and is required by the application ```

I am running windows 10 home `ver1803`
If you need more info let me know ;)

**Comment by feross** [comment]
This issue appears stale since it has been open for a while with no activity. I'm going to close it for now. If this is still issue, please feel free to leave a comment or open a new issue.
