### ISSUE TITLE
Error on  Kali Linux 

### ISSUE THREAD

**Issue by ghost** [feross/SpoofMAC#93]
```
> spoof-mac.py randomize en0
Traceback (most recent call last):
File "/usr/local/bin/spoof-mac.py", line 4, in <module>
    __import__('pkg_resources').run_script('SpoofMAC==2.1.1', 'spoof-mac.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1432, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/spoof-mac.py' not found in metadata at '/usr/local/lib/python2.7/dist-packages/SpoofMAC-2.1.1.dist-info
```

**Comment by feross** [comment]
I'm not a Python expert, so I don't know what the solution to this issue is. I would try reinstalling the package since the error appears to have something to do with the script not being able to be found, despite the metadata being there.
